Repository fossology/LicenseDb, pull requests merged in 2024-05, with the labels that each got.

#50 fix(license_patch): Fix bug in license patch request
  cmd/laas/docs/docs.go
  cmd/laas/docs/swagger.json
  cmd/laas/docs/swagger.yaml
  pkg/api/licenses.go
  pkg/models/types.go
Labels: needs test

#55 fix(docs): Fix errors in compilation of docs of struct LicensePATCHRequestJSONSchema
  cmd/laas/docs/docs.go
  cmd/laas/docs/swagger.json
  cmd/laas/docs/swagger.yaml
  pkg/models/types.go
Labels: needs test, needs code review

#52 Feat: Add /export endpoint, To export All License Json
  cmd/laas/docs/docs.go
  cmd/laas/docs/swagger.json
  cmd/laas/docs/swagger.yaml
  pkg/api/api.go
  pkg/api/licenses.go
  pkg/models/types.go
Labels: merge conflict
