Repository fossology/LicenseDb, pull requests merged in 2024-06, with the labels that each got.

#61 refactor(obligation_maps): Add transactions and refactor code
  pkg/api/obligationmap.go
Labels: needs test

#64 Feat: Docker Support for license DB
  Dockerfile
  docker-compose.yml
  entrypoint.sh
Labels: enhancement

#68 feat: Introduce Stage to Build and Push Docker Image
  .github/workflows/docker-build-push.yml
Labels: needs test, needs code review

#70 feat(obligations_preview): Create an endpoint to fetch topic and type of all obligations
  cmd/laas/docs/docs.go
  cmd/laas/docs/swagger.json
  cmd/laas/docs/swagger.yaml
  pkg/api/api.go
  pkg/api/obligations.go
  pkg/models/types.go
Labels: needs test, needs code review

#72 feat(license_preview): Created an endpoint to fetch all license shortnames
  cmd/laas/docs/docs.go
  cmd/laas/docs/swagger.json
  cmd/laas/docs/swagger.yaml
  pkg/api/api.go
  pkg/api/licenses.go
  pkg/models/types.go
Labels: needs test, needs code review
